### ISSUE TITLE
Out of interest

### ISSUE THREAD

**Issue by jrote1** [mezoni/locking#1]
Out of interest why did you use an Expando in Monitor instead of a Map?

**Comment by mezoni** [comment]
Please wait a while.
Soon will be ready the folowing features (mutexes).
- NormalMutex
- ReentrantMutex
- Conditions

The "lock" will be re-implemented (already implemented) with `ReentrantMutex`.

>> Out of interest why did you use an Expando in Monitor instead of a Map?

The `Expando` in Dart lnaguage is `WeakReferenceMap`.

Eg. (new implementation of `lock`)

```dart
part of locking;

final Expando _objects = new Expando();

Future lock(Object object, void action()) async {
  Map<Zone, Mutex> mutexes = _objects[object];
  if (mutexes == null) {
    mutexes = <Zone, Mutex>{};
    _objects[object] = mutexes;
  }

  var zone = Zone.current;
  Mutex mutex = mutexes[zone];
  if (mutex == null) {
    mutex = new ReentrantMutex();
    mutexes[zone] = mutex;
  }

  await mutex.acquire();
  try {
    await action();
  } finally {
    mutex.release();
  }
}
```

Short answer: No need worry about freeing objects.

**Comment by jrote1** [comment]
Ok makes sense thanks for your answer and Mutexes are interesting, never really looking into them.

**Comment by mezoni** [comment]
>> Ok makes sense thanks for your answer and Mutexes are interesting, never really looking into them.

In Dart they looked as very easy things.
You can look at them because I had just pushed new version.
https://github.com/mezoni/locking/blob/master/lib/src/mutex.dart

P.S.
Condition variables still not completed.
They need for solving producer/consumer problem.

Producer–consumer problem
http://en.wikipedia.org/wiki/Producer%E2%80%93consumer_problem

Better explaination.
http://en.wikipedia.org/wiki/Monitor_(synchronization)
See "Condition variables".

**Comment by jrote1** [comment]
Ok yeah looks good will look into it fully later, is the new version usable?

**Comment by mezoni** [comment]
>> Ok yeah looks good will look into it fully later, is the new version usable?

It works in packages:
- libffi6_extension
- unsafe_extension

Barback executes the transformers in a parallel but an installation of the native extension requires a compilation.
Compilation requires mutually exclusive rights.
That is, two installations cannot run simultaneously.
This is because they change current working directory.

```dart
    await runZoned(() async {
      await lock(Installer.lockObject, () async {
        try {
          var path = _resolvePackagePath(filepath);
          FileUtils.chdir(path);
          var installer = new Installer();
          await installer.install([]);
        } finally {
          FileUtils.chdir(_workingDirectory);
        }
      });
    });
```

Where the `Installer.lockObject` is a shared object from package `build_tools`.

```dart
static final lockObject = Builder.lock;
```

That is, need have a shared object.
But the shared `Mutex` are considered as the better solution (on the my opinion).
But it was written before the `Mutex` becomes available.
